name: qgan-image-generation
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - python=3
  - ipykernel
  - jupyter
  - numpy
  - pandas
  - pip
  - plotly
  - tensorflow
  - tqdm
  - pip:
    - pennylane